stages:
  - artifactory

create_artifact:
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  cache:
    paths:
      - ./.m2/repository/
  image: maven:3-jdk-8-alpine
  stage: artifactory
  script:
    - mvn --settings $MAVEN_SETTINGS_XML clean deploy -f ./code/thumbnail-generator
  only:
    - master